"""nexus-studio — the orchestration workbench (auto-orchestration / flow
editing / template testing).

A second console face, independent of ui.api (the ops console at
/console):

- api.py      /api/v1/studio/* (the pattern management face + agent
              generation SSE + the AI assistant)
- store.py    the loader for the hosted directories
              (host/config/plugins/*.py + host/config/patterns/*.yml) —
              replayed at startup/reload; a console pattern overrides the
              code version of the same code
- agent.py    LLM prompt building / fence output parsing / generated-plugin
              import validation
- static/     the build-less vanilla-JS frontend, mounted at /studio
              (PRD: docs/design/)

Design decisions (user-confirmed): plugin Python code generated by
auto-orchestration is persisted and registered automatically; only the
fixed hosted directories are loaded — no arbitrary-path loading entry.
"""

from pathlib import Path


def static_dir() -> Path:
    return Path(__file__).resolve().parent / "static"
